// Auto-generated by Supabase CLI
// Regenerate: npx supabase gen types typescript --project-id kneaniaifzgqibpajyji > src/types/database.types.ts

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
